export const platformMetrics = {
  twitter: [
    "followers",
    "following",
    "likes",
    "views",
    "retweets",
    "impressions",
    "tweets",
  ],
  facebook: ["posts", "comments", "friends", "likes"],
  instagram: ["followers", "following", "posts", "comments", "impressions"],
  tiktok: ["followers", "following", "videos", "views"],
  youtube: ["followers", "videos", "views"],
  reddit: ["posts", "karma"],
  tumblr : ["followers", "following", "posts"],
  pinterest: ["followers", "following", "pins"],
  linkedin: ["followers", "following", "posts", "comments"],
  threads: ["posts", "comments", "followers", "following"],
  telegram: ["followers", "views", "posts"],
  vk: ["followers", "following", "posts"],
  okru: ["followers", "following", "posts"],
  turkkitap: ["followers", "following", "posts", "views", "likes"],
  blogspot: ["views", "articles"],
  kizlarsoruyor: ["followers", "following", "posts"],
  balatarin: ["votes", "views", "posts"],
  virasty: ["followers", "following", "posts"],
  blogsky: ["followers", "following", "posts"],
};